name: Continuous integration

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  # all Cargo feature combinations
  ci-all:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust:
         - stable
        features:
          - "--no-default-features"
          - "--features ndarray_volumes,nalgebra_affine"
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.rust }}
          override: true
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: ${{ matrix.features }}
      - uses: actions-rs/cargo@v1
        with:
          command: test
          args: ${{ matrix.features }}

  # one Cargo feature combination (all)
  ci-minimal:
    runs-on:
     - ubuntu-latest
    strategy:
      matrix:
        rust:
          - beta
        features:
          - "--features ndarray_volumes,nalgebra_affine"
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.rust }}
          override: true
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: ${{ matrix.features }}
      - uses: actions-rs/cargo@v1
        with:
          command: test
          args: ${{ matrix.features }}

  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust:
          - stable
        features:
          - "--features ndarray_volumes,nalgebra_affine"
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.rust }}
          override: true
      - run: rustup component add clippy
      - uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: ${{ matrix.features }}
